### PR TITLE
Python2 compatibility

### PR DESCRIPTION
**Pull request by ltalirz**
Dear Cory, this is Leopold from the group of Berend Smit.
We would like to use pyIAST as part of an [AiiDA](www.aiida.net) workflow and the version of AiiDA we've been using is only python 2.7.

This PR makes pyIAST compatible with both python2 and python3. I hope this is ok?

It also adds a travis check that, so far, just installs pyIAST on python2 and python3 and imports the module (see [here](https://travis-ci.org/ltalirz/pyIAST/builds/503782101?utm_source=github_status&utm_medium=notification) for the build log and [here](https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci) for how to enable travis for your repository - only steps 1-3 apply). 
I saw you already have a few more tests in the `test/` directory that are more of the "visual" type. You might consider at some point to add some continuous integration tests whose result can be checked automatically.

I've also added an auto-formatter (yapf).
In order to apply the autoformatter (+ automatic check that the code remains python2/3 compatible), do `pip install -e .[pre-commit]; pre-commit install`. This will run the "hooks" on every commit.
If you don't like the autoformatter, let me know and I can remove it again.

### CODE REVIEW

**Comment by SimonEnsemble** [comment]
@ltalirz hi, nice to e-meet you. Great, thank you for contributing to pyIAST!

Could you possibly re-make this commit but without all of the formatting changes, then make the formatting changes later in a separate PR? The reason is that it is difficult for me to go through the many changes and see what has been changed. Most of this is formatting changes.

I agree that it would be great to have unit tests to run on Travis instead of 'visual' ones I originally had. I welcome a PR for this (converting my visual tests into unit tests)!. I will enable the Travis CI.

Thanks.

**Comment by CorySimon** [comment]
@ltalirz so now this PR is stale, can you make another PR with the formatting changes?
Thanks, I appreciate it.

Another issue: in the tests, I get the following warning from pandas. Is it okay if we change these to `.idxmin` or will this interfere with Python 2 compatibility? I know there is some way to ensure that the users have version `x` or higher pandas in the `setup.py`?

Then, I will release a new version so that `pip` sees the Python 2 compatible code. I suppose we should update the documentation now too.

```
/home/cokes/pyIAST/pyiast/isotherms.py:60: FutureWarning: 'argmin' is deprecated, use 'idxmin' instead. The behavior of 'argmin'
will be corrected to return the positional minimum in the future.
Use 'series.values.argmin' to get the position of the minimum now.
  idx_min = df_nonzero[loading_key].argmin()
```

**Comment by ltalirz** [comment]
> can you make another PR with the formatting changes?

Done in #7 

> Another issue: in the tests, I get the following warning from pandas. Is it okay if we change these to .idxmin or will this interfere with Python 2 compatibility? I know there is some way to ensure that the users have version x or higher pandas in the setup.py?

Done in #8 

>  I suppose we should update the documentation now too.

Done in #8 

> Then, I will release a new version so that pip sees the Python 2 compatible code

Yes, one the PRs are merged, please do!

**Comment by CorySimon** [comment]
@ltalirz thank you! I released a new version and updated PyPI. Please try a `pip` install on your machines to make sure it works as intended!
You're right that taking in PR's would be much easier if I had written unit tests instead of visual ones...

**Pull request closed without merging**
